services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb2/config:/etc/influxdb2
      - ./influxdb2/db:/var/lib/influxdb2