http:
  routers:
    portainer-route:
      rule: "Host(`portainer.example.com`)"
      service: portainer-service
      entryPoints:
      - websecure
      tls:
        certResolver: cloudflare

  services:
    portainer-service:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
        - url: "https://0.0.0.0:9443"

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
