# http:
#   routers:
#     uptime-router:
#       rule: "Host(`uptime.home.soniiit.net`)"
#       entryPoints: ["websecure"]
#       tls:
#         certResolver: cloudflare
#       service: "uptime-service"
#       middlewares:
#         - uptime-middleware

#   services:
#     uptime-service:
#       loadBalancer:
#         servers:
#           - url: "http://uptime-kuma3001"

#   middlewares:
#     uptime-middleware:
#       stripPrefix:
#         prefixes:
#           - "/uptime"