# Simple docker-compose.yml
# You can change your port or volume location

version: '3.3'

networks:
  traefik-nw:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    networks:
      - traefik-nw
    ports:
      - 3001:3001
    restart: always