version: "3.3"
networks:
  traefik-nw:
    external: true
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /docker/docker-compose/uptime-kuma/uptime-kuma-data:/app/data
    networks:
      - traefik-nw
    ports:
      - 3001:3001
    restart: unless-stopped