services:
  bind9:
    image: docker.io/ubuntu/bind9:9.18-23.10_edge
    container_name: bind9
    ports:
      - "53:53"
    volumes:
      - ./config:/etc/bind/
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    restart: unless-stopped