version: "3.3"
services:
  kestra:
    pull_policy: always
    stdin_open: true
    tty: true
    ports:
      - 1337:8080
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - /docker/docker-compose/kestra/data/:/app/data
    image: kestra/kestra:latest-full
    command: server local
    networks:
      - traefik-nw
    restart: unless-stopped
    environment:
      - SECRET_DISCORD_WEBHOOK=${SECRET_DISCORD_WEBHOOK}
      - SECRET_SSH-KEY=${SECRET_SSH-KEY}
networks:
  traefik-nw:
    external: true