all:
  vars:
    ansible_ssh_private_key_file: "id_rsa"
  children:
    Group1:
      hosts:
        Server1:
          ansible_host: 0.0.0.0
          ansible_user: user
          ansible_ssh_private_key_file: id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
