all:
  vars:
    ansible_ssh_private_key_file: "id_rsa"
  children:
    docker:
      hosts:
        docker-srv-mgm:
          ansible_host: 192.168.178.11
          ansible_user: soniiit
          ansible_ssh_private_key_file: id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        docker-srv-01:
          ansible_host: 192.168.178.20
          ansible_user: soniiit
          ansible_ssh_private_key_file: id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        docker-srv-02:
          ansible_host: 192.168.178.21
          ansible_user: soniiit
          ansible_ssh_private_key_file: id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    appserver:
      hosts:
        app-srv-01:
          ansible_host: 192.168.178.30
          ansible_user: soniiit
          ansible_ssh_private_key_file: id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    lxc:
      hosts:
        app-lxc-01:
          ansible_host: 192.168.178.3
          ansible_user: root
          ansible_ssh_private_key_file: id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
