version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # environment:
    #   WATCHTOWER_MONITOR_ONLY: 'true'
    #   WATCHTOWER_NOTIFICATIONS: email
    #   WATCHTOWER_NOTIFICATION_EMAIL_FROM: your_gmail
    #   WATCHTOWER_NOTIFICATION_EMAIL_TO: recipient_email
    #   WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
    #   WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
    #   WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: your_gmail
    #   WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: gmail_app_password
    # command: [CONTAINER_NAME] [CONTAINER_NAME] --interval 30 # Use to specify which containers to watch & Check evry 30 seconds for updates