version: "3"

networks:
  traefik-nw:
    external: true

services:
  web:
    image: nginx:latest
    container_name: nginx-soniiit-net
    restart: unless-stopped
    networks:
      - traefik-nw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-soniiit-net.rule=Host('soniiit.net')"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
